engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
  eslint:
    enabled: true
  fixme:
    enabled: true
exclude_paths:
  - examples/**/*
  - tests/**/*
  - examples.config.js
  - webpack.config.js
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - LICENSE.md
  - README.md
ratings:
  paths:
  - src/**/*
